name: MyFaction
main: MyFaction\MyFaction
version: "0.1-dev#1"
api: ["3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0-ALPHA3"]
load: STARTUP
author: SuperPuperSteve
description: Simple factions plugin

commands:
 faction:
  descrition: "Faction admin commands"
  permission: myfaction.faction
  
permissions:
 myfaction:
  description: "Top permsiion of MyFaction plugin"
  default: op
  
  children:
   myfaction.faction:
    description: "Allows using faction command"
    default: true